[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "finind"
version = "0.2.1"
description = "A lightweight, production-ready Python library for computing core financial technical indicators such as SMA, EMA, and RSI using numerically stable and vectorized pandas operations. Designed for quantitative research, algorithmic trading, and machine learning pipelines."
readme = "README.md"
requires-python = ">=3.9"
authors = [{name="Vaishali J Mehta"}]
dependencies = ["pandas>=1.5", "numpy>=1.23","pytest"]
license = "MIT"
license-files = ["LICEN[CS]E*"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Operating System :: OS Independent",
]
[tool.setuptools.packages.find]
where = ["src"]